yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name: str = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Class for adding groups on site """
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Вэб адрес')
    description = models.TextField(max_length=600,
                                   verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name='unique_follows',
                fields=['user', 'author'],
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='non_self_follow')
        ]


class Post(models.Model):
    """ Class for making posts with given attributes"""
    text = models.TextField(
        verbose_name="Текст поста",
        help_text="Текст нового поста"
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Название группы',
        related_name='posts',
        help_text="Группа, к которой будет относиться пост "
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    """ Class for making comments for posts with given attributes"""
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Комментарий',
        related_name='comments',
        help_text="Напишите свой комментарий"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name="Текст поста",
        help_text="Текст нового поста"
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utilites import use_paginator


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    page_obj = use_paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = use_paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", post.author)
    context = {
        "is_edit": False,
        "form": form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        "is_edit": True,
        "form": form,
        "post": post
    }
    return render(request, 'posts/create_post.html', context)


def post_detail(request, post_id: int):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = use_paginator(request, post_list)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    context = {
        'posts': post_list,
        'page_obj': page_obj,
        'author': author,
        'following': following,
        'user': request.user
    }
    return render(request, 'posts/profile.html', context)


@login_required
def follow_index(request):
    user = get_object_or_404(User, username=request.user)
    post_list = Post.objects.filter(
        author__following__user=user
    ).select_related('author', 'group')
    page_obj = use_paginator(request, post_list)
    context = {
        'page_obj': page_obj,
        'user': user
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author and (not Follow.objects.filter(
            user=request.user,
            author=author).exists()):
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактирование поста {% else %} Создание поста {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редактировать запись {% else %} Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post"
                    {% if is_edit %}
                  action="{% url 'posts:post_edit' post.pk %}"
                    {% else %}
                  action="{% url 'posts:post_create' %}"
                    {% endif %} enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                {% for field in form %}
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span> {% endif %}
                  </label>
                  <div class="form-group row my-3 p-3">
                    {{ field }}
                    <small id="{{ field.id_for_label }}-help"
                           class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  </div>
                {% endfor %}
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %} Подписки пользователя {{user.get_full_name}} {% endblock %}
{% load thumbnail %}
{% load cache %}
{% block content %}
  {% cache 20 index %}
    <h1>Подписки пользователя {{user.get_full_name}} </h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          {% thumbnail post.image "720x300" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}"
            >все записи автора </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text|truncatewords:100|linebreaksbr }}
          <a href="{% url 'posts:post_detail' post.pk %}"
          > <br> читать полностью </a>
        </p>
        {% if post.group %}
          <a href="{% url 'posts:group_posts' post.group.slug %}"
          >все записи группы </a>
        {% endif %}
        {% if not forloop.last %}
          <hr>{% endif %}
      </article>
    {% endfor %}
  {% endcache %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group.title }} {% endblock %}
{% load thumbnail %}
{% block content %}
  <h1>{{ group.title }} </h1>
  <p>{{ group.description|linebreaksbr }} </p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "720x300" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% load thumbnail %}
{% load cache %}
{% block content %}
  <h1>Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
      <ul>
        {% thumbnail post.image "720x300" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}"
          >все записи автора </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|truncatewords:100|linebreaksbr }}
        <a href="{% url 'posts:post_detail' post.pk %}"
        > <br> читать полностью </a>
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"
        >все записи группы </a>
      {% endif %}
      {% if not forloop.last %}
        <hr>{% endif %}
    </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_posts' post.group.slug %}">
              <br> все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            <br> все посты пользователя
          </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span> {{ post_count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "720x300" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if request.user == post.author %}
          <a class="btn btn-primary"
             href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
          </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">

            <form method="post" action="{% url 'posts:add_comment' post.pk %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.get_full_name }}
              </a>
            </h5>
              <p>
               {{ comment.text|linebreaksbr }}
              </p>
            </div>
          </div>
      {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя: {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts.count }} </h3>
    {% if user != author %}
      {% if following %}
        <a class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
           role="button">
          Отписаться
        </a>
      {% else %}
        <a class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
    {% endif %}
  </div>
  <div class="container py-5">
    {% for post in page_obj %}
      <article>
        <ul>
          {% if post.group %}
            <li>
              Название группы: {{ post.group }}
            </li>
          {% endif %}
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
      {% thumbnail post.image "720x300" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
        <p>
          {{ post.text|truncatewords:100|linebreaksbr }}
        <a href="{% url 'posts:post_detail' post.pk %}"> <br>
          читать полностью </a>
        </p>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи
        группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>
{% endblock %}